# Generated by Django 4.0.3 on 2022-04-03 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publish', models.DateTimeField(default=datetime.datetime(2022, 4, 3, 17, 23, 46, 875699, tzinfo=utc))),
                ('content', models.TextField()),
            ],
        ),
    ]
