# Generated by Django 4.0.3 on 2022-04-03 17:55

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='posts',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 17, 55, 15, 291147, tzinfo=utc)),
        ),
    ]
