# Generated by Django 4.0.3 on 2022-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='image',
            field=models.ImageField(default='pics/default.jpg', upload_to='pics/'),
        ),
    ]
